services:
  - type: web
    name: cuahanguarahara
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookstore.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore-db
          property: connectionString

databases:
  - name: bookstore-db
